### ISSUE TITLE
Errors during docker compose build

### ISSUE THREAD

**Issue by cesalo** [chrisvel/wreeto_official#1]
First of all it looks awesome and I'm very anxious to test it.
Is it suppose to run in an specific Linux flavor? - I'm Centos 7. I got the following error trying to run the compose build:
```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/app/wreeto/config/initializers/recaptcha.rb:2:in `block in <top (required)>'
/usr/local/bundle/ruby/2.6.0/gems/recaptcha-5.5.0/lib/recaptcha.rb:38:in `configure'
/app/wreeto/config/initializers/recaptcha.rb:1:in `<top (required)>'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/app/wreeto/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
ERROR: Service 'app' failed to build: The command '/bin/sh -c bundle exec rake assets:precompile' returned a non-zero code: 1

```

**Comment by chrisvel** [comment]
Most possibly in `config/initializers/recaptcha.rb` where initialisation happens:

```
config.site_key  = Rails.application.credentials.recaptcha[:site_key]
config.secret_key = Rails.application.credentials.recaptcha[:secret_key]
```

A Rails _master.key_ must be generated with:

```
bin/rails secret # for the first time 
bin/rails credentials:edit
```
and this structure (example):

```
recaptcha:
  site_key: "1234567890"
  secret_key: "qwertyuiop"
```

I will be moving the secrets to **.env** for consistency and faster edits, maybe deployment to k8s also in the future. 

For a quick fix you can just enter something random in the initialiser file: 

```
config.site_key  = "1234567890"
config.secret_key = "qwertyuiop"
```

I understand that not everyone will be needing to have recaptcha, so I'll update a mechanism to disable it per preference (in _.env_).

Keeping this open as a reminder.

**Comment by cesalo** [comment]
Thanks I believe that helped and was able to build it, couple of questions though:

1. It seems I can't connect from a different IP in my LAN. I got the following error initially.

> app_1       | Cannot render console from 192.168.xxx.xxx! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

I restarted and connected from the same server and I saw the login screen. How can I enable other IPs?

2. I got a initial login screen but couldn't login (tried user@email.com) - what is the admin default login?

**Comment by chrisvel** [comment]
@cesalo I added a quick fix for the initial issue. 

For the others now, the first one must be a docker configuration from your side. The `docker-compose.yml` starts Rails server and binds it to `0.0.0.0` so that must be OK. But I'll make my research and reply back If there's a bug. 

Considering your second point, the default credentials are mentioned in the Readme file. 

> The default credentials are: username **user@email.com** and password **password**.

Are you having a problem with these ones ?

**Comment by pegasy** [comment]
I got it up and running now after pulling and rebuilding but the default credentials are not correct (and can't sign up since I don't have the recapcha stuff).

**Comment by chrisvel** [comment]
Pull and re-run. Issue must be fixed now. 
I will add more tests, that's a promise! 😀

**Comment by drw72** [comment]
new build works but like those above, I cannot log in with the default credentials.

**Comment by chrisvel** [comment]
@drw72 Something must have gone wrong in the previous builds. 

Please try `docker-compose run app bundle exec rake db:drop db:migrate db:setup` to re-create the database and let me know. 

I've added a message when default user is created successfully, you can pull to get the latest commits. I've also updated the README with instructions how can you create another account. It's only a way to keep things moving now - I am going to improve the way new accounts are created.

**Comment by drw72** [comment]
worked like a charm...thank you
