### ISSUE TITLE
Install wreeto with podman on Centos/RHLE 

### ISSUE THREAD

**Issue by Crupuk** [chrisvel/wreeto_official#48]
Hi, 

On CentOs,  docker has been replaced with podman .

I have many docker image ( > 20 ) from docker.io that run fine with podman.

But when I try to install wreeto I got this error message : 

```bash
sudo podman run --name wreeto -p 8383:80   -e POSTGRES_USER=wreeto -e POSTGRES_PASSWORD=xxxxxxx -e POSTGRES_HOST=10.88.0.19 -e POSTGRES_DB=wreeto -e RAILS_ENV=production -e RACK_ENV=production  -e REDIS_HOST=10.88.0.20 -e WREETO_HOST=notes.ndd.com -e WREETO_PORT=8383  -e RAILS_MASTER_KEY=xxxxx docker.io/chrisvel/wreeto:version-2.6.2
```

And the log  :  

```
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

rake aborted!
ActiveRecord::AdapterNotSpecified: 'bundle exec production' database is not configured. Available: ["default", "development", "test", "production"]
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/connection_specification.rb:260:in `resolve_symbol_connection'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/connection_specification.rb:241:in `resolve_connection'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/connection_specification.rb:143:in `resolve'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_handling.rb:57:in `establish_connection'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/base.rb:27:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:255:in `block in load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:255:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/app/wreeto/app/models/application_record.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `block in load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:475:in `load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:373:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:195:in `const_missing'
/app/wreeto/app/models/user.rb:32:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `block in load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:475:in `load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:373:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:195:in `const_missing'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:283:in `const_get'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:283:in `block in constantize'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:281:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:281:in `inject'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:281:in `constantize'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:582:in `get'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:613:in `constantize'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:320:in `get'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:83:in `to'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:78:in `modules'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:95:in `routes'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:162:in `default_used_route'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:72:in `initialize'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:350:in `new'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:350:in `add_mapping'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `each'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `devise_for'
/app/wreeto/config/routes.rb:23:in `block in <top (required)>'
/usr/local/bundle/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/usr/local/bundle/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/usr/local/bundle/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:414:in `draw'
/app/wreeto/config/routes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:41:in `each'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:41:in `load_paths'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:20:in `reload!'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:30:in `block in updater'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/file_update_checker.rb:83:in `execute'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:10:in `execute'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
/app/wreeto/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true

rake aborted!
ActiveRecord::AdapterNotSpecified: 'bundle exec production' database is not configured. Available: ["default", "development", "test", "production"]
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/connection_specification.rb:260:in `resolve_symbol_connection'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/connection_specification.rb:241:in `resolve_connection'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/connection_specification.rb:143:in `resolve'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_handling.rb:57:in `establish_connection'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/base.rb:27:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:255:in `block in load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:255:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/app/wreeto/app/models/application_record.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `block in load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:475:in `load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:373:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:195:in `const_missing'
/app/wreeto/app/models/user.rb:32:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:476:in `block in load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:475:in `load_file'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:373:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:37:in `load_interlock'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:356:in `require_or_load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:510:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:195:in `const_missing'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:283:in `const_get'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:283:in `block in constantize'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:281:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:281:in `inject'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/inflector/methods.rb:281:in `constantize'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:582:in `get'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:613:in `constantize'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:320:in `get'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:83:in `to'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:78:in `modules'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:95:in `routes'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:162:in `default_used_route'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:72:in `initialize'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:350:in `new'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:350:in `add_mapping'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `each'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `devise_for'
/app/wreeto/config/routes.rb:23:in `block in <top (required)>'
/usr/local/bundle/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/usr/local/bundle/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/usr/local/bundle/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:414:in `draw'
/app/wreeto/config/routes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:41:in `each'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:41:in `load_paths'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:20:in `reload!'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:30:in `block in updater'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/file_update_checker.rb:83:in `execute'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/routes_reloader.rb:10:in `execute'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
/app/wreeto/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)

```

I don't know Rails, and my only experience was to install Redmine :-( .

Thanks for your help

**Comment by Crupuk** [comment]
And if I try with the latest version I got this error : 

```bash
$ sudo podman run --name wreeto -p 8383:80   -e POSTGRES_USER=wreeto -e POSTGRES_PASSWORD=xxxxxx -e POSTGRES_HOST=10.88.0.19 -e POSTGRES_DB=wreeto -e RAILS_ENV=production -e RACK_ENV=production  -e REDIS_HOST=10.88.0.20 -e WREETO_HOST=notes.ndd.com -e WREETO_PORT=8383  -e RAILS_MASTER_KEY=f21ab619787e22f6cb13d3884ca20d78 docker.io/chrisvel/wreeto:latest
Trying to pull docker.io/chrisvel/wreeto:latest...
Getting image source signatures
Copying blob 4dd8a1ae7c56 done
Copying blob 188c0c94c7c5 done
Copying blob 8b9bdda967f5 done
Copying blob dcff69af93dc done
Copying blob ba0772c8cbe1 done
Copying blob 1266e9897dbc done
Copying blob 341f42d4336d done
Copying blob c15060a315bb done
Copying blob 37ce0626eacb done
Copying blob b3f0fcb11fb6 done
Copying blob b1968c811809 done
Copying blob 77ca94beb58c done
Copying blob 7e18e9785e57 done
Copying blob 3148def3ff86 done
Copying blob a68a0beb968f done
Copying config 28e84eef6b done
Writing manifest to image destination
Storing signatures
== 20201012113301 ReplaceCategorySlugs: migrating =============================
== 20201012113301 ReplaceCategorySlugs: migrated (0.0064s) ====================

bundler: exec needs a command to run
```

And same error  with the 2.6.4 : 

```
bundler: exec needs a command to run
```

**Comment by chrisvel** [comment]
Hi @Crupuk,

I guess this happens because of the `/docker-entrypoint.sh` script. I don't have a solution for you right now, it needs a little bit of research first. Why don't you use the docker-compose file? Isn't something equivalent in podman?

**Comment by Crupuk** [comment]
Hi @chrisvel  thx for your fast reply.

No there isn't a replacement for that :-( And it's not a option to remove podman and use docker ( I have > 20 podman running for the moment ) 

Do you think you will work on this or not ? ( to know if a wait a little bit for a solution, or if I need to find a workaround / replacement ) 

Thanks for this great project !

**Comment by chrisvel** [comment]
@Crupuk yes, I will try to find a solution for this. I believe I can move the functionality of the shell script to the app itself. I'll keep you posted.

**Comment by chrisvel** [comment]
@Crupuk can you please remove the last line from the `Dockerfile` https://github.com/chrisvel/wreeto_official/blob/c463075f33ab8965786907f77b0fb866b347c990/Dockerfile#L50 ?

Then build the docker image locally with `docker build .` and run the following commands with podman in the image:

```
bundle exec rake db:create
bundle exec rake db:migrate 
bundle exec rake db:seed
```
I don't know how this is possible in podman, I guess something similar to docker like `podman run ...` while the container has been built and is up ?

**Comment by sea-odoo** [comment]
Hello @chrisvel ,

Thanks for your help, even if I try to execute this command it failed because "Podman" handle entrypoint differently :

`sudo podman run -e POSTGRES_USER=wreeto -e POSTGRES_PASSWORD=xxxxxx -e POSTGRES_HOST=10.88.0.19 -e POSTGRES_DB=wreeto -e RACK_ENV=production -e RAILS_ENV=production -e REDIS_HOST=10.88.0.20 -e WREETO_HOST=notes.ndd.come -e WREETO_PORT=8383 -e RAILS_MASTER_KEY=xxxxxx -it wreeto sh "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed"

sh: can't open 'bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed': No such file or directory
`

Also try with "cd /app/wreeto" but Podman doesn't like that...

**Comment by Crupuk** [comment]
Hello @chrisvel ,

Thanks for your help, even if I try to execute this command it failed because "Podman" handle entrypoint differently :

```
sudo podman run -e POSTGRES_USER=wreeto -e POSTGRES_PASSWORD=xxxxxx -e POSTGRES_HOST=10.88.0.19 -e POSTGRES_DB=wreeto -e RACK_ENV=production -e RAILS_ENV=production -e REDIS_HOST=10.88.0.20 -e WREETO_HOST=notes.ndd.come -e WREETO_PORT=8383 -e RAILS_MASTER_KEY=xxxxxx -it wreeto sh "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed"

sh: can't open 'bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed': No such file or directory
```

Also try with "cd /app/wreeto" but Podman doesn't like that...

**Comment by chrisvel** [comment]
@Crupuk I am working on including the entrypoint script's commands in the Dockerfile but it will need a little bit more time and effort. 

It's definitely something that will help others as well, especially people that are using NAS devices to upload a Dockerfile instead of a docker-compose one. 

If you want to hang on a bit more, it's a WIP.

**Comment by sea-odoo** [comment]
Thx :-p , no problem I will wait :-D
